name: InaTEWS Realtime Bot

on:
  schedule:
    - cron: '* * * * *'

  workflow_dispatch:

jobs:
  realtime:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: pip install -r requirements.txt

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python gempa.py

      - name: Save History
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          git add last_id.txt

          git diff --cached --quiet || git commit -m "update"

          git push
